/**
 * This file was automatically generated by the Mule ESB Maven Tools
 */
package com.jim;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import org.junit.Test;
import org.mule.DefaultMuleMessage;
import org.mule.api.MuleMessage;
import org.mule.api.client.MuleClient;
import org.mule.transport.NullPayload;
import org.mule.tck.junit4.FunctionalTestCase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;

public class ExampleFunctionalTestCase extends FunctionalTestCase {
    private static final int RECEIVE_TIMEOUT = 5000;
    private static Logger logger = LoggerFactory.getLogger(ExampleFunctionalTestCase.class);

    @Override
    protected String getConfigFile() {
        return "app-1-mule-config.xml";
    }

    @Test
    public void testConfiguration() throws Exception {
        MuleClient client = muleContext.getClient();
        HashMap<String, String> props = new HashMap<>();
        props.put("action", "stop");

        MuleMessage message = new DefaultMuleMessage(props, muleContext);
        client.dispatch("vm://in", message);
        MuleMessage result = client.request("vm://out", RECEIVE_TIMEOUT);
        assertNotNull(result);
        assertNull(result.getExceptionPayload());
        assertFalse(result.getPayload() instanceof NullPayload);

        //TODO Assert the correct data has been received
        assertEquals("Stopped flow(s): stoppable-flow Received", result.getPayloadAsString());
        logger.info("got data {}", result.getPayloadAsString());
    }
}
